
#pragma kernel CSMain

// SRG includes
#include "Core/Macros.hlsli"

RWTexture2DArray<float4> _TextureTest : SRG_PerPass(u0);

[numthreads(8, 8, 1)]
void CSMain(uint3 tid : SV_DispatchThreadID)
{
    _TextureTest[uint3(tid.xy, 0)] = float4(_TextureTest[uint3(tid.xy, 0)].r, _TextureTest[uint3(tid.xy, 0)].g * 0.5, 0, 1);
    _TextureTest[uint3(tid.xy, 1)] = float4(_TextureTest[uint3(tid.xy, 1)].r, _TextureTest[uint3(tid.xy, 1)].r * 0.5, 0, 1);
}
